### ISSUE TITLE
Cannot run project in Rider/Visual Studio

### ISSUE THREAD

**Issue by pazurkota** [GrzegorzKarczewski/BMI-Calculator#6]
I can't run this project neither from Rider or Visual Studio

If i debug project, i've got this error:
`System.Data.SQLite.SQLiteException: „SQL logic error
no such table: Users”` - `UserRepository.cs`, line 126

And as Visual Code says, this exeption has been reported in the following files:
- `UserRepsitory.cs` at `GetUserNames()`
- `MainWindow.xaml.cs` at `PopulateList()`
- `MainWindow.xaml.cs` at `MainWindow()`

Is there any extra steps like creating database or it's just a bug (or a feature, who knows)?
Or I'm doing something wrong?

**Comment by GrzegorzKarczewski** [comment]
I'm offline for now so i cannot run this , but i would guess the bug is related probably that the code is reading from table before creating table. It was probably because i added/changed database related functions while having already created database so i didnt had that bug before. I will check on that later

**Comment by pazurkota** [comment]
Okay, if you need any more information, just tell me, ill try to provide it

**Comment by GrzegorzKarczewski** [comment]
I've put some checks for the app to check if table 'Users' exist. Should work now, please test it and let me know if we can close the issue. Thanks for seeing this. It taught me a good lesson :)

**Comment by pazurkota** [comment]
Yea, everything works now as should
Tested in Rider and Visual Studio

**Comment by GrzegorzKarczewski** [comment]
Nice, so i will close this issue :)

**Comment by GrzegorzKarczewski** [comment]
Nice, so i will close this issue :)
